[build]
  base = "/"
  command = "cd frontend && npm install && npm run build"
  publish = "frontend/dist"
  functions = "functions"

[dev]
  command = "cd frontend && npm run dev"
  targetPort = 5173